### ISSUE TITLE
Issue with some words

### ISSUE THREAD

**Issue by diegobernardes** [anaelcarvalho/elasticsearch-analysis-rslp#1]
I got some issues with some words using this stemmer. 'porquinho' get stemmed to 'porq' instead of 'porc'.

Reading the original c implementation there is a 'steprules.txt' file that has a rule for this case, maybe it is not implemented in the java version, i don't have time now to look the code and find the issue :[

**{"quinho",4,"c"},**

```
# Step 4: Augmentative/Diminutive Reduction
{   "Augmentative", 0, 1, {},
    {"díssimo",5},
    {"abilíssimo",5},
    {"íssimo",3},
    {"ésimo",3},
    {"érrimo",4},
    {"zinho",2},
        {"quinho",4,"c"},
    {"uinho",4},
    {"adinho",3},
    {"inho",3,"",{"caminho","cominho"}},
    {"alhão",4},
    {"uça",4},
    {"aço",4,"",{"antebraço"}},
    {"aça",4},
    {"adão",4},
    {"idão",4},
    {"ázio",3,"",{"topázio"}},
    {"arraz",4},
    {"zarrão",3},
    {"arrão",4},
    {"arra",3},
    {"zão",2,"",{"coalizão"}},
    {"ão",3,"",{"camarão","chimarrão","canção","coração","embrião","grotão","glutão",
                   "ficção","fogão","feição","furacão","gamão","lampião","leão","macacão","nação",
                   "órfão","orgão","patrão","portão","quinhão","rincão","tração",
                   "falcão","espião","mamão","folião","cordão","aptidão","campeão",
                   "colchão","limão","leilão","melão","barão","milhão","bilhão","fusão",
                   "cristão","ilusão","capitão","estação","senão"}}};
```

**Comment by anaelcarvalho** [comment]
Hi -

This rule ('quinho') is in fact implemented in the plugin; it is not applied for the word 'porquinho' because minimum stem size is 4 ('por' has 3 characters and thus the next rule, 'uinho', is applied, resulting in 'porq').

However, I'm not sure whether stem size should be checked before the substitution or after ('por' vs 'porc') - I will check the documentation for clarification.

**Comment by anaelcarvalho** [comment]
Ok, after reviewing the original paper, I believe the implementation is correct as per the original algorithm.

However - I do believe accuracy would be greater if minimum stem size is reduced to 2 for this rule. While this may generate stemming issues for some words (e.g. 'mesquinho'), these can be later added to the exception list.

I will make the code change and generate a new version later on - thanks for the input!

**Comment by diegobernardes** [comment]
Hmm didn't know that it was already implemented, anyway, thanks :+1:
